### ISSUE TITLE
Why branch off from onnx_pb?

### ISSUE THREAD

**Issue by jinchenglee** [FL33TW00D/steelix#14]
It is not an issue, but I cannot find a better place to raise the question. Thus here.
Also, I'm greenhorn in Rust, so question can be stupid. 

I wonder why steelix branched off (I assume?) from onnx_pb to steelix version of onnx_pb?

**Comment by FL33TW00D** [comment]
> It is not an issue, but I cannot find a better place to raise the question. Thus here. Also, I'm greenhorn in Rust, so question can be stupid.
> 
> I wonder why steelix branched off (I assume?) from onnx_pb to steelix version of onnx_pb?

I like complete control :)

**Comment by jinchenglee** [comment]
I see the onnx_pb crate has not been updated for ~3 years unfortunately, so you've got good reason. Maybe a PR to update the onnx_pb, just in case.
